package com.bazaarvoice.bvandroidsdk;

/**
 * <p>
 *  Authentication that clients configured for
 *  <a href="http://knowledge.bazaarvoice.com/wp-content/conversations/en_US/Collect/site_authentication.html">Site Authentication</a>
 *  should use. You can check which authentication configuration you have by following
 *  <a href="http://knowledge.bazaarvoice.com/wp-content/conversations/en_US/Learn/user_authentication.html#determine-your-authentication-configuration">these steps</a>.
 * </p>
 * <p>
 *  You will need to implement this to be able to retrieve an encrypted User Authentication String (UAS)
 *  from your companies backend.
 * </p>
 * <p>
 *  Your company may have an existing endpoint to retrieve this from, if your web team has already implemented
 *  this. If not you will need to follow <a href="http://knowledge.bazaarvoice.com/wp-content/conversations/en_US/Collect/site_authentication.html">these steps</a>.
 * </p>
 */
public class SiteAuthenticationProvider implements AuthenticationProvider {
  private final String uas;

  /**
   * @param uas User Authentication String generated by <a href="http://knowledge.bazaarvoice.com/wp-content/conversations/en_US/Collect/site_authentication.html#step-3-generate-a-user-authentication-string-uas">these steps</a>.
   */
  public SiteAuthenticationProvider(String uas) {
    this.uas = uas;
  }

  public String getUas() {
    return uas;
  }
}